### ISSUE TITLE
Understand if use-secondary-gids LCMAPS behaviour can be reproduced in Argus 1.7

### ISSUE THREAD

**Issue by andreaceccanti** [argus-authz/argus-documentation#13]
Before 1.7.0, Argus provided a "useSecondaryGroupNamesForMapping" option that could
be used to have mapping behaviour consistent with LCMAPS configured with option "-do_not_use_secondary_gids".

This task is to understand whether:
- the useSecondaryGroupNamesForMapping option is still meaningful in Argus 1.7.0
- adapt documentation so that is consistent with Argus 1.7.0 behaviour, if needed

Related GGUS ticket:
https://ggus.eu/index.php?mode=ticket_info&ticket_id=129136

Related PR:
#9

**Comment by jouvin** [comment]
I am one of the person who is at the origin of the `do_not_use_secondary_gids` option in LCMAPS, if I'm right. We have not yet upgraded our ARGUS server to 1.7.x but I can image that we'll face Massimo's issue described in GGUS ticket. I'll try in a next comment to summarize what our problem was and why we needed this config.
